import chessPieces from "./chessPieces";
export default {
  black: {
    pawn1: chessPieces.black.pawn,
    pawn2: chessPieces.black.pawn,
    pawn3: chessPieces.black.pawn,
    pawn4: chessPieces.black.pawn,
    pawn5: chessPieces.black.pawn,
    pawn6: chessPieces.black.pawn,
    pawn7: chessPieces.black.pawn,
    pawn8: chessPieces.black.pawn,
    pawn9: chessPieces.black.pawn,
    rook1: chessPieces.black.rook,
    rook2: chessPieces.black.rook,
    knight1: chessPieces.black.knight,
    knight2: chessPieces.black.knight,
    bishop1: chessPieces.black.bishop,
    bishop2: chessPieces.black.bishop,
    queen: chessPieces.black.queen,
    king: chessPieces.black.king,
  },
  white: {
    pawn1: chessPieces.white.pawn,
    pawn2: chessPieces.white.pawn,
    pawn3: chessPieces.white.pawn,
    pawn4: chessPieces.white.pawn,
    pawn5: chessPieces.white.pawn,
    pawn6: chessPieces.white.pawn,
    pawn7: chessPieces.white.pawn,
    pawn8: chessPieces.white.pawn,
    pawn9: chessPieces.white.pawn,
    rook1: chessPieces.white.rook,
    rook2: chessPieces.white.rook,
    knight1: chessPieces.white.knight,
    knight2: chessPieces.white.knight,
    bishop1: chessPieces.white.bishop,
    bishop2: chessPieces.white.bishop,
    queen: chessPieces.white.queen,
    king: chessPieces.white.king,
  },
};
